Message {
  channel:
   TextChannel {
     type: 'text',
     deleted: false,
     id: '668310460520595511',
     name: 'general',
     position: 0,
     parentID: '668310460520595509',
     permissionOverwrites: Collection [Map] {},
     topic: null,
     nsfw: false,
     lastMessageID: '676988477748805633',
     lastPinTimestamp: null,
     rateLimitPerUser: 0,
     guild:
      Guild {
        members: [Collection],
        channels: [Collection],
        roles: [Collection],
        presences: [Collection],
        deleted: false,
        available: true,
        id: '668310460520595506',
        name: 'Miko Queue',
        icon: null,
        splash: null,
        region: 'us-east',
        memberCount: 2,
        large: false,
        features: [],
        applicationID: null,
        afkTimeout: 300,
        afkChannelID: null,
        systemChannelID: '668310460520595511',
        embedEnabled: undefined,
        verificationLevel: 0,
        explicitContentFilter: 0,
        mfaLevel: 0,
        joinedTimestamp: 1579411938937,
        defaultMessageNotifications: 'ALL',
        ownerID: '139587871467241474',
        _rawVoiceStates: Collection [Map] {},
        emojis: Collection [Map] {} },
     messages: Collection [Map] { '676988477748805633' => [Circular] },
     _typing: Map {} },
  deleted: false,
  id: '676988477748805633',
  type: 'DEFAULT',
  content: 'hello',
  author:
   User {
     id: '139587871467241474',
     username: 'Miko',
     discriminator: '0117',
     avatar: '14922dd7d9e60e2dadd222cfb9bf1dc9',
     bot: false,
     lastMessageID: '676988477748805633',
     lastMessage: [Circular] },
  member:
   GuildMember {
     guild:
      Guild {
        members: [Collection],
        channels: [Collection],
        roles: [Collection],
        presences: [Collection],
        deleted: false,
        available: true,
        id: '668310460520595506',
        name: 'Miko Queue',
        icon: null,
        splash: null,
        region: 'us-east',
        memberCount: 2,
        large: false,
        features: [],
        applicationID: null,
        afkTimeout: 300,
        afkChannelID: null,
        systemChannelID: '668310460520595511',
        embedEnabled: undefined,
        verificationLevel: 0,
        explicitContentFilter: 0,
        mfaLevel: 0,
        joinedTimestamp: 1579411938937,
        defaultMessageNotifications: 'ALL',
        ownerID: '139587871467241474',
        _rawVoiceStates: Collection [Map] {},
        emojis: Collection [Map] {} },
     user:
      User {
        id: '139587871467241474',
        username: 'Miko',
        discriminator: '0117',
        avatar: '14922dd7d9e60e2dadd222cfb9bf1dc9',
        bot: false,
        lastMessageID: '676988477748805633',
        lastMessage: [Circular] },
     joinedTimestamp: 1579408030411,
     _roles: [],
     serverDeaf: false,
     serverMute: false,
     selfMute: undefined,
     selfDeaf: undefined,
     voiceSessionID: undefined,
     voiceChannelID: undefined,
     speaking: false,
     nickname: null,
     lastMessageID: '676988477748805633',
     lastMessage: [Circular],
     deleted: false },
  pinned: false,
  tts: false,
  nonce: '676988476704423936',
  system: false,
  embeds: [],
  attachments: Collection [Map] {},
  createdTimestamp: 1581477030933,
  editedTimestamp: null,
  reactions: Collection [Map] {},
  mentions:
   MessageMentions {
     everyone: false,
     users: Collection [Map] {},
     roles: Collection [Map] {},
     _content: 'hello',
     _client:
      Client {
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: 10,
        options: [Object],
        rest: [RESTManager],
        dataManager: [ClientDataManager],
        manager: [ClientManager],
        ws: [WebSocketManager],
        resolver: [ClientDataResolver],
        actions: [ActionsManager],
        voice: [ClientVoiceManager],
        shard: null,
        users: [Collection],
        guilds: [Collection],
        channels: [Collection],
        presences: Collection [Map] {},
        user: [ClientUser],
        readyAt: 2020-02-12T03:10:22.369Z,
        broadcasts: [],
        pings: [Array],
        _timeouts: [Set],
        _intervals: [Set] },
     _guild:
      Guild {
        members: [Collection],
        channels: [Collection],
        roles: [Collection],
        presences: [Collection],
        deleted: false,
        available: true,
        id: '668310460520595506',
        name: 'Miko Queue',
        icon: null,
        splash: null,
        region: 'us-east',
        memberCount: 2,
        large: false,
        features: [],
        applicationID: null,
        afkTimeout: 300,
        afkChannelID: null,
        systemChannelID: '668310460520595511',
        embedEnabled: undefined,
        verificationLevel: 0,
        explicitContentFilter: 0,
        mfaLevel: 0,
        joinedTimestamp: 1579411938937,
        defaultMessageNotifications: 'ALL',
        ownerID: '139587871467241474',
        _rawVoiceStates: Collection [Map] {},
        emojis: Collection [Map] {} },
     _members: null,
     _channels: null },
  webhookID: null,
  hit: null,
  _edits: [] }