
const WORLDS = {
  '1001': { name: 'Anvil Rock', population: 'Medium' },
  '1002': { name: 'Borlis Pass', population: 'Medium' },
  '1003': { name: 'Yak\'s Bend', population: 'Full' },
  '1004': { name: 'Henge of Denravi', population: 'High' },
  '1005': { name: 'Maguuma', population: 'VeryHigh' },
  '1006': { name: 'Sorrow\'s Furnace', population: 'Medium' },
  '1007': { name: 'Gate of Madness', population: 'Medium' },
  '1008': { name: 'Jade Quarry', population: 'Full' },
  '1009': { name: 'Fort Aspenwood', population: 'VeryHigh' },
  '1010': { name: 'Ehmry Bay', population: 'Medium' },
  '1011': { name: 'Stormbluff Isle', population: 'VeryHigh' },
  '1012': { name: 'Darkhaven', population: 'High' },
  '1013': { name: 'Sanctum of Rall', population: 'Medium' },
  '1014': { name: 'Crystal Desert', population: 'VeryHigh' },
  '1015': { name: 'Isle of Janthir', population: 'Medium' },
  '1016': { name: 'Sea of Sorrows', population: 'High' },
  '1017': { name: 'Tarnished Coast', population: 'Full' },
  '1018': { name: 'Northern Shiverpeaks', population: 'High' },
  '1019': { name: 'Blackgate', population: 'Full' },
  '1020': { name: 'Ferguson\'s Crossing', population: 'Medium' },
  '1021': { name: 'Dragonbrand', population: 'High' },
  '1022': { name: 'Kaineng', population: 'Medium' },
  '1023': { name: 'Devona\'s Rest', population: 'Medium' },
  '1024': { name: 'Eredon Terrace', population: 'Medium' },
  '2001': { name: 'Fissure of Woe', population: 'Medium' },
  '2002': { name: 'Desolation', population: 'VeryHigh' },
  '2003': { name: 'Gandara', population: 'VeryHigh' },
  '2004': { name: 'Blacktide', population: 'Medium' },
  '2005': { name: 'Ring of Fire', population: 'Medium' },
  '2006': { name: 'Underworld', population: 'Medium' },
  '2007': { name: 'Far Shiverpeaks', population: 'VeryHigh' },
  '2008': { name: 'Whiteside Ridge', population: 'Medium' },
  '2009': { name: 'Ruins of Surmia', population: 'Medium' },
  '2010': { name: 'Seafarer\'s Rest', population: 'Full' },
  '2011': { name: 'Vabbi', population: 'Medium' },
  '2012': { name: 'Piken Square', population: 'VeryHigh' },
  '2013': { name: 'Aurora Glade', population: 'High' },
  '2014': { name: 'Gunnar\'s Hold', population: 'High' },
  '2101': { name: 'Jade Sea [FR]', population: 'VeryHigh' },
  '2102': { name: 'Fort Ranik [FR]', population: 'Medium' },
  '2103': { name: 'Augury Rock [FR]', population: 'High' },
  '2104': { name: 'Vizunah Square [FR]', population: 'VeryHigh' },
  '2105': { name: 'Arborstone [FR]', population: 'Medium' },
  '2201': { name: 'Kodash [DE]', population: 'Full' },
  '2202': { name: 'Riverside [DE]', population: 'VeryHigh' },
  '2203': { name: 'Elona Reach [DE]', population: 'VeryHigh' },
  '2204': { name: 'Abaddon\'s Mouth [DE]', population: 'VeryHigh' },
  '2205': { name: 'Drakkar Lake [DE]', population: 'VeryHigh' },
  '2206': { name: 'Miller\'s Sound [DE]', population: 'Medium' },
  '2207': { name: 'Dzagonur [DE]', population: 'Medium' },
  '2301': { name: 'Baruch Bay [SP]', population: 'VeryHigh' }
};

module.exports = {
  WORLDS
}
